### ISSUE TITLE
Incorporate dagitty/ggdag

### ISSUE THREAD

**Issue by malcolmbarrett** [GerkeLab/ShinyDAG#2]
Hi folks,

I'm VERY excited to see this. I'm not sure when I'd have the time to do this, but what do you think about me submitting a PR to have one of the export options be to ggdag (https://github.com/malcolmbarrett/ggdag)? It would also be good to export dagitty code (I see that you're using it already for analysis). 

Let me know!
Malcolm

**Comment by malcolmbarrett** [comment]
(By the way, I think you should think about turning this into a proper package in addition to hosting on shinyapps)

**Comment by tgerke** [comment]
Thanks for the feedback! We love ggdag and will certainly have it properly cited/promoted when we officially preprint/roll this thing out. We benefitted immensely from you already figuring out all that do-calculus code. And you're right: exporting daggity code should be straightforward since we're already in that format along the way. (@jhcreed thanks in advance!)

As for the package, we've entertained the idea, but it gets messy very quickly because the LaTeX/imagemagick install on the backend can be very finicky. Actually got some key support from shinyapps.io to update imagemagick so that this could even work there. We fear frustration from end-users if they can't get the thing to run because of system-wide dependencies. Other thoughts here are absolutely welcome.

**Comment by malcolmbarrett** [comment]
Great! Yes, I understand about the backend stuff. That can be tricky. 

Again, I'm very excited about your work on this. I intended to do something similar, and this is looking so nice, I wouldn't even think to implement my own now. Which is why I greedily want to sneak ggdag in!

**Comment by jhcreed** [comment]
Quick warning: the code here is not the most up to date version on shinyapps.io. I would be happy to add in the option to export to ggdag and then push the update here so you can take a look and give any comments!

**Comment by malcolmbarrett** [comment]
Oh, gotcha. Yes, if this all fits into your vision for this project, I'd love to see it! I imagine if the underlying analysis is already in dagitty, it will be fairly easy to export to either ggdag or raw dagitty code.

**Comment by malcolmbarrett** [comment]
Awesome work, @jhcreed and @tgerke. Looking forward to playing with it more!
